spring:
  application:
    name: weather_ecosystem_service

application:
  weather:
    base-url: "https://goweather.herokuapp.com/weather/"
  producer:
    base-url: "http://we-producer-service:8082/v1/producer/"